baseURL = "https://ashishji.is-a.dev/blog/"
languageCode = "en-us"
title = "Break · Build · Repeat"
theme = "PaperMod"

enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true

