baseURL = "https://ashishji.is-a.dev/blog/"
languageCode = "en-us"
title = "Break Â· Build Â· Repeat"
theme = "PaperMod"

enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
    Title = "Hi, I'm Ashish ðŸ‘‹"
    Content = "I document my journey in coding, security, and projects. Here I share writeups of CTF challenges, experiments, and system internals. This is a space to learn, build, and repeat."

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/ashishjii"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ashishverma-cs"
